apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eks/k8s.yaml
  - eks/hpa.yaml
  - eks/pdb.yaml

images:
  - name: REPLACE_API_IMAGE
    newName: 719030485343.dkr.ecr.ap-northeast-2.amazonaws.com/rps-arena-api
    newTag: 88c3995
  - name: REPLACE_WEB_IMAGE
    newName: 719030485343.dkr.ecr.ap-northeast-2.amazonaws.com/rps-arena-web
    newTag: 88c3995
